version: "3.9"
services:
  worker:
    build: .
    environment:
      BOT_TOKEN: $BOT_TOKEN
      API_ID: $API_ID
      API_HASH: $API_HASH
      STRING_SESSION: $STRING_SESSION
      ASSISTANT_ID: $ASSISTANT_ID
